# Generated by Django 6.0.5 on 2026-05-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('is_default', models.BooleanField(default=False, help_text="The fallback property when the user hasn't picked one. Exactly one per user.")),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['owner', 'name'], name='properties__owner_i_b5e054_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'slug'), name='unique_owner_slug'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='unique_default_property_per_user')],
            },
        ),
    ]
