# Generated by Django 6.0.5 on 2026-05-17 19:04

import apps.receipts.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Öppen'), ('locked', 'Låst')], default='open', max_length=16)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.receipts.models.receipt_image_upload_path)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date', models.DateField(help_text='The receipt date — used to derive the TaxYear.')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('source_scan_job_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID of the scanning.ReceiptScanJob this Receipt was confirmed from.', null=True)),
                ('confirmed_at', models.DateTimeField(help_text='When the user confirmed the receipt. Required — receipts cannot exist unconfirmed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('tax_year', models.ForeignKey(blank=True, help_text='Auto-derived from `date`. Never set manually.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='receipts.taxyear')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taxyear',
            index=models.Index(fields=['owner', '-year'], name='receipts_ta_owner_i_7947fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxyear',
            constraint=models.UniqueConstraint(fields=('owner', 'year'), name='unique_owner_year'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['owner', '-date'], name='receipts_re_owner_i_1f4349_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['owner', '-created_at'], name='receipts_re_owner_i_7d5468_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tax_year', '-date'], name='receipts_re_tax_yea_765232_idx'),
        ),
    ]
