# Generated by Django 6.0.5 on 2026-05-17 20:26

import apps.receipts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cloudinary_secure_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirmed_at',
            field=models.DateTimeField(help_text='When the user confirmed the receipt. Required.'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy local-storage path. Cloudinary-uploaded receipts leave this empty.', null=True, upload_to=apps.receipts.models.receipt_image_upload_path),
        ),
    ]
