# Generated by Django 6.0.5 on 2026-05-18 07:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_cloudinary_secure_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-computed: total_amount - vat_amount. Set in save().', max_digits=12),
        ),
    ]
