# Generated by Django 6.0.5 on 2026-05-14 08:19

import apps.receipts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_usersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('preview_ready', 'Preview ready'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('image', models.ImageField(upload_to=apps.receipts.models.receipt_scan_job_upload_path)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['owner', '-created_at'], name='receipts_re_owner_i_7d5468_idx'),
        ),
        migrations.AddField(
            model_name='receiptscanjob',
            name='confirmed_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='receiptscanjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_scan_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='receiptscanjob',
            index=models.Index(fields=['user', 'status', '-created_at'], name='receipts_re_user_id_b28231_idx'),
        ),
    ]
