# Generated by Django 6.0.5 on 2026-05-18 07:58

from decimal import Decimal

from django.db import migrations


def forward(apps, schema_editor):
    Receipt = apps.get_model("receipts", "Receipt")
    for receipt in Receipt.objects.all():
        total = receipt.total_amount or Decimal("0.00")
        vat = receipt.vat_amount or Decimal("0.00")
        receipt.net_amount = total - vat
        receipt.save(update_fields=["net_amount"])


def backward(apps, schema_editor):
    # Nothing to do — leaving net_amount populated is harmless on rollback.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0003_receipt_net_amount"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]