# Generated by Django 6.0.5 on 2026-05-18 09:31

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0005_backfill_net_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="net_amount",
        ),
        migrations.AddField(
            model_name="receipt",
            name="net_amount",
            field=models.GeneratedField(
                expression=models.F("total_amount") - models.F("vat_amount"),
                output_field=models.DecimalField(
                    decimal_places=2, max_digits=12
                ),
                db_persist=True,
            ),
        ),
    ]
