# Generated by Django 6.0.5 on 2026-05-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('receipts', '0006_alter_receipt_net_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxyear',
            name='unique_owner_year',
        ),
        migrations.AddField(
            model_name='receipt',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Denormalized convenience — always == tax_year.property.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='taxyear',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='taxyear',
            name='owner',
            field=models.ForeignKey(help_text='Denormalized convenience — always == property.owner.', on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taxyear',
            index=models.Index(fields=['property', '-year'], name='receipts_ta_propert_483195_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxyear',
            constraint=models.UniqueConstraint(fields=('property', 'year'), name='unique_property_year'),
        ),
    ]
