# Generated by Django 6.0.5 on 2026-05-18 14:11

from django.db import migrations


def forward(apps, schema_editor):
    """Backfill property on all existing TaxYears and Receipts."""
    User = apps.get_model("accounts", "User")
    Property = apps.get_model("properties", "Property")
    TaxYear = apps.get_model("receipts", "TaxYear")
    Receipt = apps.get_model("receipts", "Receipt")

    for user in User.objects.all():
        # Ensure default property exists
        default_prop = Property.objects.filter(owner=user, is_default=True).first()
        if default_prop is None:
            default_prop = Property.objects.create(
                owner=user,
                name="Min fastighet",
                slug="min-fastighet",
                is_default=True,
            )

        # Backfill TaxYears
        TaxYear.objects.filter(owner=user, property__isnull=True).update(
            property=default_prop
        )

        # Backfill Receipts
        Receipt.objects.filter(owner=user, property__isnull=True).update(
            property=default_prop
        )


def backward(apps, schema_editor):
    """Reversible no-op — property column simply becomes null on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_remove_taxyear_unique_owner_year_receipt_property_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
