# Generated by Django 6.0.5 on 2026-05-18 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('receipts', '0008_backfill_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ordinal_number',
            field=models.PositiveIntegerField(blank=True, help_text="Löpnummer inom (property, tax_year). Allocated atomically on first save. Stable for the receipt's lifetime — gaps appear when receipts are deleted.", null=True),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['property', 'tax_year', 'ordinal_number'], name='receipts_re_propert_1e55bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('ordinal_number__isnull', False)), fields=('property', 'tax_year', 'ordinal_number'), name='unique_property_year_ordinal'),
        ),
    ]
