# Generated by Django 6.0.5 on 2026-05-18 16:10

from django.db import migrations


def forward(apps, schema_editor):
    """Assign ordinal_number = 1, 2, 3, ... to existing receipts within
    each (property, tax_year), in date-then-created_at order."""
    Receipt = apps.get_model("receipts", "Receipt")

    seen_groups: dict[tuple[int, int], int] = {}
    receipts = Receipt.objects.filter(ordinal_number__isnull=True).order_by(
        "property_id", "tax_year_id", "date", "created_at"
    )
    for receipt in receipts:
        key = (receipt.property_id, receipt.tax_year_id)
        next_n = seen_groups.get(key, 0) + 1
        seen_groups[key] = next_n
        receipt.ordinal_number = next_n
        receipt.save(update_fields=["ordinal_number"])


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_receipt_ordinal_number_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
