# Generated by Django 6.0.5 on 2026-05-17 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('review_ready', 'Review ready'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('cloudinary_secure_url', models.URLField(max_length=1024)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=32)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='receipts.receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_scan_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='scanning_re_user_id_286356_idx'), models.Index(fields=['status', 'queued_at'], name='scanning_re_status_52a637_idx')],
            },
        ),
    ]
